---
title: "Publishing in a journal"
---

## Publishing in a journal

### Initial submission

Unless there is a compelling reason, the first author should also serve as the corresponding author. The first author will coordinate all required manuscript formatting for the specific journal. Additionally, some journal outlets have required documents (e.g., author acknowledgement) that will require all authors to sign.

#### Preprint

Posting a preprint usually occurs simultaneously with the initial submission of a project to an outlet for publication. The purpose of preprints is to get results out as early as possible while manuscripts go through the review process. Preprints are usually not a problem with journals, but that is not universally the case, so always check the outlet’s preprint policy prior to preprinting manuscripts. Preprints should never be used for manuscripts that are considered in a “rough” state. An easy rule of thumb is the following: if the preprint were accepted to a high-visibility journal with no changes whatsoever, would you be embarrassed by the state it is in? If the answer is “yes”, it is not ready for preprinting. Preprints are public; they should be high quality.

### Revisions

After receiving an R&R from a journal, the lead author should combine all reviewer comments into two documents: 1) a word document with reviewer and comment numbers clearly delineated (titled: reviewer_response.docx), and 2) a reviewer comment matrix (titled: reviewer_matrix.xlxs).

#### Comment matrix

A reviewer comment matrix is a useful tool for identifying areas of overlap between the comments of different reviewers (i.e., areas that must be addressed). Create a comment matrix as follows:

| Theme (optional) | Section      | Reviewer #1 | Reviewer #2 | Reviewer #3 |
|------------------|--------------|-------------|-------------|-------------|
|                  | Intro.       | Comment #1  |             |             |
|                  | Lit. Review. | Comment #2  |             |             |
| Power analysis   | Methods      | Comment #3  |             |             |
| Power analysis   | Methods      |             | Comment #1  |             |
| Power analysis   | Methods      |             |             | Comment #1  |

: Example comment matrix

The comment matrix should be in long format with respect to the section, so there will be multiple entries for some sections (possibly multiple section entries for a single reviewer). Once all the comments are added, comments that are common across reviewers can be merged into the same row to simply the matrix as follows:

| Theme (optional) | Section      | Reviewer #1 | Reviewer #2 | Reviewer #3 |
|------------------|--------------|-------------|-------------|-------------|
|                  | Intro.       | Comment #1  |             |             |
|                  | Lit. Review. | Comment #2  |             |             |
| Power analysis   | Methods      | Comment #3  | Comment #1  | Comment #1  |

: Example comment matrix (last row condensed)

Finally, if multiple entries for a section are present in the matrix, an optional “theme” column can be useful for organizing specific topics within a specific section. (Protip: add a filter to the matrix to make rearranging comments easy). The comment matrix is an extremely useful tool for viewing all the comments from an R&R simultaneously (instead of linearly) and can help the team rank/prioritize the comments (or themes). An example comment matrix is provided in the research_prcesses directory.

The reviewer response document should list all the reviewer comments in the order they are received. For example, Reviewer 1 comments will come first and be presented in the same order as received. This helps the reviewers quickly check if their comments/questions were addressed.

#### Response letter

Although not required by all journals, drafting a response letter is a nice touch. The response letter should be addressed to the editor that you have been corresponding with. The response letter should provide additional context if needed. It can serve as the introduction for the reviewer response document.
