---
title: "Wrapping up a project"
---

## Wrapping up a project (post acceptance)

Save a copy of the final PDF version from the publisher in the “Published Articles” folder on OneDrive (OneDrive > Research > Published Articles). Follow the naming convention as established (YEAR – Article Title). 

### Open Access

ALERRT has funding available to pay for open access (aka: article processing costs). The lead author should coordinate with the Director of Research to make sure the correct funding line is used. The lead author should then complete a purchase request form to start the process.

### Media posts

The lead author of a project (in collaboration with key members of the team) should draft a list of highlights from the study to be posted on various personal/official media sites. This list of highlights should be forwarded to James Keith (director of external relations) to be released upon publication of the project. The same highlights should be shared by the lead (or a designated team member) on social media sites (e.g., X, LinkedIn). Tag all authors and ALERRT in social media posts. All authors should repost/share the original post to increase awareness.

### Copy analysis directory to the ALERRT Research GitHub

If the publication is using original data that is still in use for another project, wait to upload the analysis directory until the other project(s) have been completed. Once it is ready, change the project repository to “public” so it is available. 

### Write a gist for the RR website

A “gist” (or summary) should be a more verbose version of the highlights of the project drafted for media use. It should contain a few elements: 1) a study motivation, 2) the approach, 3) findings (highlights), 4) implications, and 5) all relevant links (e.g., article link, GH repo). If the media picks up an article, links to those pieces should be added to the gist as well. An example gist is located in the “research process” folder and on the current research section of the ALERRT website (https://alerrt.org/reading).

### Draft a short article for the Tactical Science Substack

The Substack article allows for expansion beyond a “gist” writeup. Pete will add his $.02 description at the end of the Substack article – describing the relevance. 

Move the project folder from the OneDrive current_projects directory to the past_projects directory. 


