---
title: "Executing a project"
---


## File structure

All projects really get going when they get a dedicated directory. Start by setting up a new directory for the project in the “current projects” directory of the research drive on OneDrive. Always use “snake case” (e.g., project_example) when naming directories. Within the main project directory, there should be three subdirectories: analysis, manuscript, and docs.

### Analysis directory

This directory is where all the analysis files (e.g., code, data, results, figures) are going to be housed. Every analysis subdirectory should contain four additional subdirectories: 1) code, 2) input, 3) output, and 4) temp. All project code (e.g., an Rproj file, R scripts) is in “code” directory. All data required to conduct the analysis should be in the “input” directory. The “output” directory should contain two subdirectories, “results” and “figures”, for tabular/text-based and graphical results, respectively. The “temp” directory is meant to house all temporary, intermediate, or else incomplete results—only when results are considered final do they get assigned to an output directory.

### Manuscript directory

This directory is where the manuscript is housed. The filename of the actual manuscript should simply be “manuscript” and should have no versioning in its name. The idea is to have the manuscript itself be a living document and to periodically create ‘freezes’ of it that can be used as a record when major changes are implemented (e.g., adding a new section). The main document itself should never actually change names, and no other version of the manuscript should be edited. Two subdirectories should be located here as well. First, the “archive” directory should contain all the ‘freezes’ (versioning of freezes is best achieved by appending the date [e.g., “_mm_dd_yy”] to the end of the manuscript filename [manuscript_01_29_26.docx]). Second, a “submissions” directory should contain individual subdirectories for each outlet the manuscript is submitted to. Name each subdirectory after the journal (e.g., jcj for Journal of Criminal Justice). After the manuscript is prepared for a submission, a submission-specific freeze should be saved in the appropriate submission directory. Each submission should be kept distinct within an outlet’s directory (e.g., a “journal_outlet” directory might contain subdirectories for “submission_1” and “submission_2” if the project received an R&R after its initial submission). 

### Docs directory

This directory contains all project files that are not directly used in the project analysis or manuscript write-up. At least two subdirectories should go here: “lit” for all the project-specific journal articles and “admin” for all the other documents needed to conduct the project (e.g., IRB, analysis plan/preregistration, informed consent, schedules). Additional subdirectories can be added as need. For example, a “media” subdirectory can house relevant media (e.g., videos) used for the project if needed. 

After setting up a project, you should have a file structure that looks like this:

::: {style="margin-left: 20em;"}
```text
example_proj
├── analysis
│   ├── code
│   ├── input
│   ├── output
│   │   ├── figures
│   │   └── results
│   └── temp
├── docs
│   ├── admin
│   └── lit
└── manuscript
    ├── archive
    └── submissions
```
:::

Add files as needed, but all projects should have that basic structure at its core. A template file structure is available in the current projects OneDrive folder. 

<div style="text-align: center;">
{{< downloadthis resources/file_structure.zip dname="file_structure" label="Download file structure template"  type="primary">}}
</div>

When creating a new project folder, copy and paste the template file structure into the new project folder so you do not have to create it from scratch. 

ADD NOTE ABOUT ARCHIVE FOLDERS



